### ISSUE TITLE
Cant login - login failed

### ISSUE THREAD

**Issue by darthgus** [ieuanmeredith/Sim-Stat-Tracker#3]
Cant login - login failed

Hey mate - wanted to give your software a go, and it wont seem to let me login! Tried 4-5 times.. my password is def right as i was on iracing at the same time, logged out and re-typed it in and it worked.

Not sure - it is during the 24h race unless they disabled something because of that?

**Comment by ieuanmeredith** [comment]
Hadn't seen this until now sorry! I'll have to dig into it and find out what is going on!

**Comment by ieuanmeredith** [comment]
Just to update this, iRacing have changed something on their end and I'm working with them to find a resolution asap

**Comment by darthgus** [comment]
Yea I noticed another add on had to do a release in June for something like
Auth had been modified or something like that...

**Comment by ieuanmeredith** [comment]
Fixed in https://github.com/ieuanmeredith/Sim-Stat-Tracker/releases/tag/v1.1.4

**Comment by darthgus** [comment]
Confirmed works great now! :) Thanks!
